name: flat

on:
  push:
    paths:
      - .github/workflows/flat.yaml # Only run a new workflow every time this file (flat.yaml) file changes
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # Run once a month
    
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Setup deno
      uses: denoland/setup-deno@main
      with:
        deno-version: v1.x
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Fetch data
      uses: githubocto/flat@v3
      with:
        http_url: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vS7CgV6dlXXi7re9fkLg0ZOm5vs3OqFmVNk0irPx5xXz-tIrqSl6WFCxsbdRmeFD5ZhGCO0GDl7x3og/pub?gid=0&single=true&output=csv'
        downloaded_filename: data/impact-assesment.csv
    - name: Fetch data
      uses: githubocto/flat@v3
      with:
        http_url: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQMGdVltk1u6mfSPIxgkZHCNKK3uUZTWBqY6gIVQZ0Y1sjYK_--9-EZUj-cdjGoJXvzazd_OxHtTJo0/pub?output=csv'
        download_filename: data/on-ground-contacts.csv
    - name: Fetch data
      uses: githubocto/flat@v3
      with:
        http_url: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRgeZpPDTIYSe4zlk4CppIc4UzXZCx-rvK-j3smOxW_GjZXhVPabNH8JeHEePZ-QjhqXJQdiQjBK8KB/pub?gid=0&single=true&output=csv'
        download_filename: data/vendor-list.csv
